// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yemysbtfgocmehyzabvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbXlzYnRmZ29jbWVoeXphYnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjA3MjIsImV4cCI6MjA2OTYzNjcyMn0.RILhk6OfJEA78ztGGcIv9KwS9mi7X0z3E_YqEMqDpjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});